### ISSUE TITLE
How to apply prediction model to external set

### ISSUE THREAD

**Issue by yamasakih** [gnina/libmolgrid#10]
Hi,

The examples of tests/test_torch_cnn.py and README.md are very easy to understand for me.

However, I do not know what should I do when applying a prediction model to an external set (cf. test set).

The `next_batch` method of `molgrid.ExampleProvider` seems to generate more than the number of data (repeatly). Is it possible to generate exactly the number of test sets?
Now, I use `for statements` to generate the number of test sets with `batch_size = 1`.

Please let me know if there are other means.

Thanks for your help.

**Comment by dkoes** [comment]
Using a for loop with a batch size of one is perfectly reasonable.  Make sure you do not have balancing, shuffling, or any other settings that modify the input order on.

**Comment by yamasakih** [comment]
>Using a for loop with a batch size of one is perfectly reasonable. Make sure you do not have balancing, shuffling, or any other settings that modify the input order on.

Yes, I set `balancing=False` and `shuffling=False`.

Thanks so much for your prompt comment!
