### ISSUE TITLE
Issue when install libmolgrid from source

### ISSUE THREAD

**Issue by JonasLi-19** [gnina/libmolgrid#114]
My system is CentOS7 (not root user), the libmolgrid-master.zip is installed and unzipped in /data2/rjli/software/libmolgrid
After mkdir build && cd build, I run the following command in anaconda environment base:
cmake -DCMAKE_INSTALL_PREFIX=/data2/rjli ..

Error information is : 
CMake Error at /data2/rjli/anaconda3/lib/cmake/Boost-1.78.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /data2/rjli/anaconda3/lib/cmake/boost_python-1.78.0/boost_python-config.cmake

  but it set boost_python_FOUND to FALSE so package "boost_python" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_python310.so.1.78.0 (3.10, Boost_PYTHON_VERSION=3.6)

  * libboost_python310.a (3.10, Boost_PYTHON_VERSION=3.6)

Call Stack (most recent call first):
  /data2/rjli/anaconda3/lib/cmake/Boost-1.78.0/BoostConfig.cmake:262 (boost_find_component)
  /data2/rjli/software/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/FindBoost.cmake:448 (find_package)
  python/CMakeLists.txt:17 (find_package)

### ABOUT BOOST
I tried hard to solve this issue for days, including build boost_1_71_0 from source using python3.10 in anaconda/bin, using the command below:
./bootstrap.sh --with-libraries=all --with-python=/data2/rjli/anaconda3/bin/python3 --with-python-version=3.10 --with-python-root=/data2/rjli/anaconda3/lib/python3.10 --with-toolset=gcc

then add the following in the project-config.jam:
_using python : 3.10 : "/data2/rjli/anaconda3/lib/python3.10": /data2/rjli/anaconda3/include/python3.10 : /data2/rjli/anaconda3/lib;_

but when run ./b2 there is always some libs that were skipped: libboost_python310.a 

finally I choose to give up using installed boost from source, but I do not know how to do next...

I tried installing libmolgrid from source because I have network trouble in CentOS server that could not download libmolgrid automatically when installinf Gnina (our group is in China mailand).
IS THERE ANY OTHER METHODS COULD BE ALRIGHT FOR ME TO USE TO INSTALL GNINA IN MY SYSTEM?

**Comment by RMeli** [comment]
Hello. Have you tried installing `boost` within your conda environment (`conda install -c conda-forge boost`) and [pointing CMake](https://cmake.org/cmake/help/latest/module/FindBoost.html#hints) to the right location?

Alternatively, you might try the **experimental** Spack support described in https://github.com/gnina/gnina/pull/184 (but also requires internet access, and has never been tested on CentOS7).

**Comment by RMeli** [comment]
@JonasLi-19 to me the error messages you get seem to indicate that CMake does not find a version of `boost` compatible with the Python interpreter it finds. I'd double check the Python interpreter found by CMake and make sure it is the one you expect.

Since you have a complex environment with system packages and an Anaconda distribution, you likely need to help CMake a bit by setting the corresponding variables (such as `BOOST_ROOT` etc, `Python_EXECUTABLE` etc).

**Comment by RMeli** [comment]
I can confirm this is the case; I just run into the same issue with `spack install libmolgrid`, with a Python 3.11 `conda` environment active.

It seems that `libmolgrid`'s CMake has a strong preference for the system:
```bash
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.11.so (found version "3.11.2") 
-- Found PythonInterp: /usr/bin/python3.11 (found version "3.11.2") 
CMake Error at /home/rmeli/spack/opt/spack/linux-ubuntu23.04-zen4/gcc-11.3.0/boost-1.82.0-gvrkquvhcqglqad6anmrgolrzkwjspmm/lib/cmake/Boost-1.82.0/Boost
Config.cmake:141 (find_package):
  Found package configuration file:

    /home/rmeli/spack/opt/spack/linux-ubuntu23.04-zen4/gcc-11.3.0/boost-1.82.0-gvrkquvhcqglqad6anmrgolrzkwjspmm/lib/cmake/boost_python-1.82.0/boost_pyt
hon-config.cmake

  but it set boost_python_FOUND to FALSE so package "boost_python" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_python310.so.1.82.0 (3.10, Boost_PYTHON_VERSION=3.11)

  * libboost_python310.a (3.10, Boost_PYTHON_VERSION=3.11)

Call Stack (most recent call first):
  /home/rmeli/spack/opt/spack/linux-ubuntu23.04-zen4/gcc-11.3.0/boost-1.82.0-gvrkquvhcqglqad6anmrgolrzkwjspmm/lib/cmake/Boost-1.82.0/BoostConfig.cmake:
262 (boost_find_component)
  /home/rmeli/spack/opt/spack/linux-ubuntu23.04-zen4/gcc-11.3.0/cmake-3.26.3-xm7jqizk3hey32gkxk7o6vg46l4giddn/share/cmake-3.26/Modules/FindBoost.cmake:
594 (find_package)
  python/CMakeLists.txt:17 (find_package)


-- Configuring incomplete, errors occurred
```

You can see it finds the `libboost_python310` library from Spack's Python, but `PythonInterp` is from `/usr/bin/`. This is likely what's happening to you too, as mentioned above.

Setting the Python executable explicitly when running CMake with `-DPYTHON_EXECUTABLE=PATH_TO_YOUR_PYTHON_EXECUTALBE` should fix the issue.

**Comment by JonasLi-19** [comment]
Hello, sorry to come up this question for you but I still get a problem when "make install" the libmolgrid in a specific newly generated empty folder: /data2/rjli/libmolgrid (not the libmolgrid-master folder)

    Although I have installed all the dependencies (the openbabel3 and boost installed in anaconda3; gcc7.4.0;cmake 3.18.0), 
    and successfully run the "**cmake** -DCMAKE_INSTALL_PREFIX=/data2/rjli/libmolgrid -DPYTHON_EXECUTABLE=/data2/rjli/anaconda3/bin/python3.10 -DOPENBABEL3_INCLUDE_DIR=/data2/rjli/anaconda3/include/openbabel3 -DOPENBABEL3_LIBRARIES=/data2/rjli/anaconda3/lib/libopenbabel.so ..",
    and "**make**",
    I still finally came across a fatal error when "make install" like:
-- Installing: /data2/rjli/libmolgrid/include/libmolgrid/common.h
-- Installing: /data2/rjli/libmolgrid/include/libmolgrid/grid_io.h
-- Installing: /data2/rjli/libmolgrid/include/libmolgrid/cartesian_grid.h
-- Installing: /data2/rjli/libmolgrid/include/libmolgrid/config.h
**fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Cannot obtain version number from git.**

### Does these information in cmake matter?
CMake Warning at test/CMakeLists.txt:31 (add_executable):
  Cannot generate a safe runtime search path for target test_quaternion_cpp
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib64 may be hidden by files in:
      /data2/rjli/anaconda3/lib

  Some of these libraries may not be found correctly.


CMake Warning at test/CMakeLists.txt:31 (add_executable):
  Cannot generate a safe runtime search path for target
  test_coordinateset_cpp because files in some directories may conflict with
  libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib64 may be hidden by files in:
      /data2/rjli/anaconda3/lib

  Some of these libraries may not be found correctly.


CMake Warning at test/CMakeLists.txt:31 (add_executable):
  Cannot generate a safe runtime search path for target test_transform_cpp
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib64 may be hidden by files in:
      /data2/rjli/anaconda3/lib

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /data2/rjli/software/libmolgrid/build


### Does this "include deprecated" information in "make" matter?
In file included from /myhome/software/libmolgrid/test/test_transform.cpp:10:0:
/myhome/anaconda3/include/boost/test/floating_point_comparison.hpp:14:77: note: #pragma message: This header is deprecated. Use <boost/test/tools/floating_point_comparison.hpp> instead.
 BOOST_HEADER_DEPRECATED( "<boost/test/tools/floating_point_comparison.hpp>" )

**Comment by JonasLi-19** [comment]
By the way, assigning  -DPYTHON_EXECUTABLE=PATH_TO_YOUR_PYTHON_EXECUTALBE  is helpful! Thanks @RMeli

**Comment by RMeli** [comment]
I'm glad it helped. The installation error (is it actually an error or just a warning?) seems pretty clear:

> You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.

It also suggests possible solutions:

* You can choose a different installation directory (with `-DCMAKE_INSTALL_PREFIX`)
* You can add the installation directory to the PYTHONPATH environment
variable (if you are happy with where things are installed despite the warning)

**Comment by JeniFoo** [comment]
I also met whis problem when in python 
>>> import molgrid

It raises Fail information:
~/anaconda3/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so: symbol cudaGraphInstantiateWithFlags, version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference
Failed to import torch.

Is this because I did not have pytorch installed?

**Comment by JonasLi-19** [comment]
To summarize, I finished build the libmolgrid by the following steps after install openbabel in conda

1.add the necessary libs location into ~/.bashrc
export LD_LIBRARY_PATH=/data2/rjli/anaconda3/envs/py36/lib:$LD_LIBRARY_PATH
export CPLUS_INCLUDE_PATH=/data2/rjli/anaconda3/envs/py36/include:$CPLUS_INCLUDE_PATH

2.
cmake -DCMAKE_INSTALL_PREFIX=/data2/rjli -DPYTHON_EXECUTABLE=/data2/rjli/anaconda3/envs/py36/bin-DOPENBABEL3_INCLUDE_DIR=/data2/rjli/anaconda3/envs/py36/include/openbabel3 -DOPENBABEL3_LIBRARIES=/data2/rjli/anaconda3/envs/py36/lib/libopenbabel.so ..
