### ISSUE TITLE
SystemError importing molgrid

### ISSUE THREAD

**Issue by niccolo93** [gnina/libmolgrid#115]
Hi,

I just installed `molgrid`  via `pip`, but when I try to import the module with python the following exception is raised:
`SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function`.

Could you please help me figure out how to fix this error?

OS:    Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

python: 3.11.3

Thanks!

**Comment by dkoes** [comment]
This appears to be a bug that was introduced in python 3.11 and has been fixed in boost 1.83:
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1885088.html

It should be fixable by building molgrid with a newer version of boost or downgrading python.

**Comment by dkoes** [comment]
Try this:
`pip install molgrid==0.5.3.dev2`

**Comment by niccolo93** [comment]
It worked, thank you very much for your help!
