### ISSUE TITLE
How can I visualize my voxel grid 

### ISSUE THREAD

**Issue by drorhunvural** [gnina/libmolgrid#118]
After generating the voxel grid, I wish to visualize it as shown in the following examples. How can I create a grid visualization based on protein features or as a main whole grid?

![Screenshot 2023-12-30 181809](https://github.com/gnina/libmolgrid/assets/26056864/b2205fab-1f29-4136-954e-a772376651a8)
[[1](https://www.nature.com/articles/s42003-020-01350-0)]

![Screenshot 2023-12-30 182334](https://github.com/gnina/libmolgrid/assets/26056864/b85d6565-8e02-4643-bb49-e9e258279f4c)
[[2](https://www.nature.com/articles/s41467-022-28327-3)]

[[3](https://gnina.github.io/libmolgrid/about.html)]  ![Screenshot 2024-01-02 140629](https://github.com/gnina/libmolgrid/assets/26056864/8a280c2e-fa42-4ad9-9d48-b236e4e6deb3)

**Comment by dkoes** [comment]
You can output grids as dx files which is a standard grid format that can be visualized with pymol, vmd, 3dmol, etc.

https://gnina.github.io/libmolgrid/python/index.html?highlight=write_dx_grids#molgrid.write_dx_grids
