### ISSUE TITLE
errors during make gnina

### ISSUE THREAD

**Issue by bellstwohearted** [gnina/libmolgrid#13]
While I am using CentOS7, anaconda3 and Boost1.67 and cuda-9.0, RDkit has been successfully compiled, and for gnina cmake, everything seems to be ok. When I perform this make command to compile gnina, there are two problems:

`~/gnina/build/libmolgrid-prefix/src/libmolgrid/include/libmolgrid/atom_typer.h:13:10: fatal error: openbabel/elements.h: No such file or directory`

`The dependency target "pycaffe" of target "pytest" does not exist`

Can anyone figure out where the problem is?

**Comment by dkoes** [comment]
For the first error you need to build the still-in-development openbabel 3.0.

**Comment by bellstwohearted** [comment]
> 
> 
> For the first error you need to build the still-in-development openbabel 3.0.

Thanks, I'll try to build the new version of obabel.
