### ISSUE TITLE
OpenBabel 3

### ISSUE THREAD

**Issue by RMeli** [gnina/libmolgrid#16]
The OpenBabel master branch now contains the alpha release of OpenBabel 3, therefore `FindOpenBabel2.cmake` does not work anymore.

I'm working on a solution, but it's taking more time than expected...

**Comment by RMeli** [comment]
The new version can be found by updating `FindOpenBabel2.cmake`,
```
-- Found Open Babel include files at /usr/local/include/openbabel3
-- Found Open Babel library at /usr/local/lib/libopenbabel.so
```
but the version check in `` appears to be problematic:
```
Documents/git/libmolgrid/src/atom_typer.cpp:15:6: error: user-defined literal in preprocessor expression
 #if (OB_VERSION >= OB_VERSION_CHECK(2,4,90))
      ^~~~~~~~~~
Documents/git/libmolgrid/src/atom_typer.cpp:15:6: error: user-defined literal in preprocessor expression
 #if (OB_VERSION >= OB_VERSION_CHECK(2,4,90))
      ^~~~~~~~~~

```

**Comment by dkoes** [comment]
The version check should be fixed in the latest version of openbabel master.
