### ISSUE TITLE
Shared Pointer Question

### ISSUE THREAD

**Issue by keranaslam90** [gnina/libmolgrid#3]
Hello,
I have question regarding your implementation. I was looking for library which generates examples of batches exactly like here. Mainly, I have problem implementing passing a std.shared_ptr to python class using boost python.
I compiled your library and tried to see how this can be done and when i executed this line:
x=molgrid.FileMappedGninaTyper(data+"/recmap")
#passing shared_ptr
e = molgrid.ExampleProvider(x,data_root=datadir+"/structs")
it throws this error:
TypeError: No registered converter was able to produce a C++ rvalue of type std::shared_ptr<libmolgrid::AtomTyper> from this Python object of type FileMappedGninaTyper

I am using ubuntu default boost but this is exactly the problem which I am trying to solve in my code

@dkoes 
@Jsunseri

**Comment by dkoes** [comment]
Whoops, looks like I never wrote a test for that functionality and it didn't "just work".  I've pushed a fix.
