### ISSUE TITLE
libmolgrid on OS X?

### ISSUE THREAD

**Issue by koshkabb** [gnina/libmolgrid#31]
Hello!
I've been trying to install libmolgrid on OS X and failing miserably, and, before I spend more time on this I just want to make sure: is libmolgrid meant to work only on Linux?

Thank you!

**Comment by dkoes** [comment]
Yes, at least for now.

**Comment by koshkabb** [comment]
Oh wow, thank you for replying so quickly! Great, I'll use it on docker then !
