### ISSUE TITLE
Question about center of the grid

### ISSUE THREAD

**Issue by koshkabb** [gnina/libmolgrid#33]
Hello,

I would just like to confirm that I understood something correctly. When using this forward method in GridMaker 
`forward((GridMaker)arg1, (Example)example, (Grid4f)grid[, (float)random_translation=0.0[, (bool)random_rotation=False]]) → None `

it says in the documentation that the grid center will be the center of the last coordinate set before transformation. Will this always be the center of the ligand?

As a side note, this method in the documentation has an extra parameter 
"param center:
grid center to use, if not provided will use center of the last coordinate set before transformation"

but the method doesn't have this parameter. Is the method wrong, or is the documentation wrong?

Thank you!

**Comment by dkoes** [comment]
Hmm.. the way the documentation is worded is a bit ambiguous.  The center of the last set of coordinates (presumably ligand) will be used.

There are versions of the forward method that take a center.  I'm not sure why the parameters listed in the python docs don't match the signature of their respective method. @Jsunseri  can you look into this?

**Comment by Jsunseri** [comment]
Fixed in 7b977ac. The parameters in the Python docs were previously taken from the underlying C++ function, which takes an optional grid_center argument that isn't exposed in Python; instead the Python version always uses the default value. The Python docstring now reflects this.

**Comment by koshkabb** [comment]
Great, thank you!
