### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by hnljq** [gnina/libmolgrid#34]
-----------------------------------------------------------------
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- The CUDA compiler identification is NVIDIA 9.0.176
-- Check for working C compiler: /mnt1/lijinqiang/conda/env/gnina/bin/x86_64-conda_cos6-linux-gnu-cc
-- Check for working C compiler: /mnt1/lijinqiang/conda/env/gnina/bin/x86_64-conda_cos6-linux-gnu-cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /mnt1/lijinqiang/conda/env/gnina/bin/x86_64-conda_cos6-linux-gnu-c++
-- Check for working CXX compiler: /mnt1/lijinqiang/conda/env/gnina/bin/x86_64-conda_cos6-linux-gnu-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Found Git: /usr/bin/git
-- Current git revision is 57f737ab4bb65627101989f28270f1d936ece289
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found version "9.0")
-- Boost  found.
-- Found Boost components:
   regex;unit_test_framework;program_options;system;filesystem;iostreams
-- Found Open Babel include files at /usr/local/include/openbabel3
-- Found Open Babel library at /lib64/libopenbabel.so
Setting openbabel found TRUE
-- Found PythonLibs: /usr/lib64/libpython3.6m.so (found version "3.6.8")
-- Found PythonInterp: /mnt1/lijinqiang/conda/env/gnina/bin/python3.6 (found version "3.6.7")
CMake Error at /usr/local/boost/lib/cmake/Boost-1.72.0/BoostConfig.cmake:120 (find_package):
  Found package configuration file:

    /usr/local/boost/lib/cmake/boost_python-1.72.0/boost_python-config.cmake

  but it set boost_python_FOUND to FALSE so package "boost_python" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_python27.so.1.72.0 (2.7, Boost_PYTHON_VERSION=3.6)

  * libboost_python27.a (2.7, Boost_PYTHON_VERSION=3.6)

Call Stack (most recent call first):
  /usr/local/boost/lib/cmake/Boost-1.72.0/BoostConfig.cmake:185 (boost_find_component)
  /usr/local/share/cmake-3.14/Modules/FindBoost.cmake:266 (find_package)
  python/CMakeLists.txt:17 (find_package)

-- Configuring incomplete, errors occurred!

------------------------------------------------------
I use python3.6 and camke3.14 and boost1.72 , what is the problem? please help me

**Comment by dkoes** [comment]
Is boost python installed (e.g. `/usr/lib/x86_64-linux-gnu/libboost_python-py36.so`)?
If it isn't in a standard location, you may have to specify where it is on the cmake commandline.

**Comment by hnljq** [comment]
-----------------------------------------------------------------
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- The CUDA compiler identification is NVIDIA 9.0.176
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Current git revision is 57f737ab4bb65627101989f28270f1d936ece289
-- Boost  found.
-- Found Boost components:
   regex;unit_test_framework;program_options;system;filesystem;iostreams
CMake Error at /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake:120 (find_package):
  Could not find a package configuration file provided by "boost_python3"
  (requested version 1.72.0) with any of the following names:

    boost_python3Config.cmake
    boost_python3-config.cmake

  Add the installation prefix of "boost_python3" to CMAKE_PREFIX_PATH or set
  "boost_python3_DIR" to a directory containing one of the above files.  If
  "boost_python3" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake:185 (boost_find_component)
  /usr/local/share/cmake-3.12/Modules/FindBoost.cmake:261 (find_package)
  python/CMakeLists.txt:14 (find_package)


-- Configuring incomplete, errors occurred!
---------------------------------------------------------------------------
now I have installed boost with python3.6，but cmake still error. Could you help me?

**Comment by dkoes** [comment]
Have you tried setting boost_python3_DIR to the appropriate directory?
