### ISSUE TITLE
does libmolgrid automatically center the grid around ligand?

### ISSUE THREAD

**Issue by yangxiufengsia** [gnina/libmolgrid#50]
Hi, 

I want to predict the binding pose using the method described your CNN paper.  But I want to ask how to make the receptor and ligand grid centered around the binding pocket? or libmolgrid automatically center the grid around ligand?

Thank you.

**Comment by dkoes** [comment]
It depends which forward method you use in the GridMaker class.  Some will take a transformation, including the center.  The higher level versions (like in the tutorial) will calculate the center from the last coordinate set in a passed example (which is usually the ligand).
