### ISSUE TITLE
visualization of grid density of protein-ligand 

### ISSUE THREAD

**Issue by yangxiufengsia** [gnina/libmolgrid#51]
Hi prof. Koes,

I am training a CNN model for predicting the binding pose. Also, I plan to visualize the generated grid density of the input protein-ligand 3d data. 

If libmolgrid provides some function that we can directly use to visualize the grid density? or are there any source code available from gnina github repos?

Thank you!

**Comment by dkoes** [comment]
I'll have to figure out why this isn't showing up in the online documentation, but there are writers (and readers) for dx files.  See `molgrid.write_dx_grids` and `molgrid.write_dx`.  You can then use your favorite molecular visualization tool (e.g. PyMOL, VMD) to view the dx files.

**Comment by yangxiufengsia** [comment]
Thank you Prof. koes. I will try then.

**Comment by yangxiufengsia** [comment]
Hi prof.koes

I tried molgrid.write_dx_grids() function, but it didn't work with error messages.
I found the function is defined as follows:
write_dx_grids(prefix, data.get_type_names(), grid, batch_info[0].grid_center, gmaker.get_resolution(), scale);

could you give me an example of the above parameters used in this defined functio?
especially, I don't understand the the second parameter: data.get_types_names(), is it obtained from example_provider?

Thanks a lot!

**Comment by dkoes** [comment]
what is the type of grid?  It is reporting as AtomGrid which isn't something in libmolgrid.  It needs to be of type molgrid.Grid4f.

**Comment by yangxiufengsia** [comment]
I used this type of grid: 
grid = AtomGrid(
                        values=np.array(grid_data),
                        channels=grid_channels,
                        center=lig_struct.center,
                        resolution=grid_maker.get_resolution(),)

Is this wrong right? I still did not get the meaning of the parameters in write_dx_grids function.
I also have several other questions.
1. what is molgrid.Grid4f?   
2. I know, libmolgrid can automatically calculate the center of the binding pocket by lig_struct.center.
but what if i don't input ligand, how libmolgrid calculate the center of binding pocket?
I am new beginner, sorry for lots of very questions.

**Comment by dkoes** [comment]
What is AtomGrid?  It is not part of molgrid, so one generally would not expect passing it to a molgrid function to work. A Grid4f is a 4D grid.

You can provide the center of the grid.  If you are using a function that calculates the center for you, it will take the center of the last molecule specified.

**Comment by yangxiufengsia** [comment]
Prof. Koes , Thank you for helping solve my questions. I used AtomGrid defined in your  liGAN repos, and will check more details of the source code.

**Comment by dkoes** [comment]
If it is AtomGrid from the liGAN repository use its to_dx method.

**Comment by yangxiufengsia** [comment]
Thank you prof. koes. i have found it from liGAN repository.

**Comment by yangxiufengsia** [comment]
Hi prof.Koes,

- I tried to_dx() function in liGAN repos and obtained the .dx files. Then I used pymol to visualize the generated .dx files. But I got very strange 3d grid density (white and back colored only, shown in the attached image), is this correct?  

<img width="329" alt="スクリーンショット 2021-03-10 172429" src="https://user-images.githubusercontent.com/15882935/110744149-8ee72280-827c-11eb-8887-dd922bfa5557.png">

- How did you obtain the following visualization figure in your 3d-cnn binding pose prediction paper: 

<img width="290" alt="スクリーンショット 2021-03-10 170356" src="https://user-images.githubusercontent.com/15882935/110744221-aa522d80-827c-11eb-9957-cc47c3ca9598.png">

 

- Are there any specific reasons to define the grid density using the following formula in your paper?

<img width="249" alt="スクリーンショット 2021-03-11 152019" src="https://user-images.githubusercontent.com/15882935/110744615-5267f680-827d-11eb-93c4-72ab4d9cb4c4.png">


Looking forward to your reply. Thank you.

**Comment by dkoes** [comment]
That figure is using VMD and showing multiple levels of isosurfaces (which you can do in pymol as well).   Some resources:
https://pymolwiki.org/index.php/Isosurface
https://pymolwiki.org/index.php/Volume

The density function was chosen to be a Gaussian that smoothly goes to exactly zero at 1.5 the radius.

**Comment by yangxiufengsia** [comment]
thanks a lot prof. koes. I have another question regarding one of your recent paper: deepfrag (https://www.biorxiv.org/content/10.1101/2021.01.07.425790v1).  
How to modify the grid density definition A(d,r) to other definitions similar with voxelization methods described in section 3.2.2 in your above paper? 
It is needed to redefine from your libmolgrid source code?  Looking forward to your reply. sorry for so many questions.

**Comment by dkoes** [comment]
Harrison didn't use libmolgrid, he wrote is own gridding code.  libmolgrid supports Gaussian+quadratic, truncated Gaussian, and boolean gridding.
