### ISSUE TITLE
Question about atom_typer.cpp

### ISSUE THREAD

**Issue by alwinbucher** [gnina/libmolgrid#55]
Hi,

Thank you for the awesome repository! I just had a quick question regarding a few lines in [atom_typer.cpp](https://github.com/gnina/libmolgrid/blob/master/src/atom_typer.cpp), specifically the code snippet below:

```
switch(a->GetAtomicNum()) {
case 1:
  ename =  a->IsPolarHydrogen() ? "HD" : "H";
  break;
case 6:
  if(a->IsAromatic()) ename = "A";
  break;
case 7:
  if(a->IsHbondAcceptor()) ename = "NA";
  break;
case 8:
  ename = "OA";
  break;
case 16:
  if(a->IsHbondAcceptor()) ename = "SA";
  break;
case 34:
  ename = "S"; //historically selenium is treated as sulfur  ¯\_(ツ)_/¯
  break;
}
```

It seems to me as if the `ename` variable gets set to "OA" for any type of oxygen atom, no matter its hydrogen-bond-acceptor status. Is this intended behaviour? If so, why?

Equally, it seems to me that as a consequence the first two of the cases below will never occur:
```
case OxygenXSDonor: //O_O_O_D,
case Oxygen: //O_O_O_P,
  ret = Hbonded ? OxygenXSDonor : Oxygen;
  break;
case OxygenXSDonorAcceptor: //O_OA_O_DA, also an autodock acceptor
case OxygenXSAcceptor: //O_OA_O_A, also an autodock acceptor
  ret = Hbonded ? OxygenXSDonorAcceptor : OxygenXSAcceptor;
  break;
```
Is this simply hardcoding the fact that at least one of the lone pairs on the oxygen should be available to act as a hydrogen-bond receptor? At least I can't think of a counterexample to that straight away... Anyway, I thought I should check just to be sure.

**Comment by dkoes** [comment]
Yes, I believe you are right - oxygen is always an acceptor, sometimes a donor-acceptor.  We are trying to match legacy atom typing schemes which do not necessarily make sense.  You'll note the default GninaTyping schemes coalesce the redundant types:
```
Oxygen OxygenXSAcceptor 
OxygenXSDonorAcceptor OxygenXSDonor
```
