### ISSUE TITLE
libmolgrid fails at make

### ISSUE THREAD

**Issue by mercadde** [gnina/libmolgrid#58]
Trying to build libmolgrid from source with GNU compilers 8.4.0.
The cmake stage is successful, I've previously built OpenBabel following the given instructions here: https://github.com/gnina/gnina 

I have set the variable to OpenBabel for header and libs and my cmake commands looks like:
cmake -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.2/bin/nvcc -DOPENBABEL3_INCLUDE_DIR=/mnt/shared/releases/compiled/OpenBabel/include -DOPENBABEL3_LIBRARIES=/mnt/shared/releases/compiled/OpenBabel/lib -DCMAKE_INSTALL_PREFIX=/mnt/shared/releases/compiled/Libmolgrid ..

In the make stage I get the following errors when trying to build **test_gridmaker_cpp**:

CMakeFiles/test_coordinateset_cpp.dir/test_coordinateset.cpp.o: In function `vectortyper::test_method()':
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:36: undefined reference to `OpenBabel::OBConversion::OBConversion(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:37: undefined reference to `OpenBabel::OBMol::OBMol()'
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:38: undefined reference to `OpenBabel::OBConversion::Read(OpenBabel::OBBase*, std::istream*)'
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:37: undefined reference to `OpenBabel::OBMol::~OBMol()'
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:36: undefined reference to `OpenBabel::OBConversion::~OBConversion()'
CMakeFiles/test_coordinateset_cpp.dir/test_coordinateset.cpp.o: In function `vectortyper_invoker()':
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:36: undefined reference to `OpenBabel::OBConversion::OBConversion(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:37: undefined reference to `OpenBabel::OBMol::OBMol()'
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:38: undefined reference to `OpenBabel::OBConversion::Read(OpenBabel::OBBase*, std::istream*)'
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:37: undefined reference to `OpenBabel::OBMol::~OBMol()'
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:36: undefined reference to `OpenBabel::OBConversion::~OBConversion()'
CMakeFiles/test_coordinateset_cpp.dir/test_coordinateset.cpp.o: In function `vectortyper::test_method()':
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:37: undefined reference to `OpenBabel::OBMol::~OBMol()'
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:36: undefined reference to `OpenBabel::OBConversion::~OBConversion()'
CMakeFiles/test_coordinateset_cpp.dir/test_coordinateset.cpp.o: In function `vectortyper_invoker() [clone .cold.228]':
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:37: undefined reference to `OpenBabel::OBMol::~OBMol()'
/mnt/shared/releases/source/libmolgrid/test/test_coordinateset.cpp:36: undefined reference to `OpenBabel::OBConversion::~OBConversion()'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::ElementIndexTyper::get_atom_type_index(OpenBabel::OBAtom*) const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:211: undefined reference to `OpenBabel::OBElements::GetCovalentRad(unsigned int)'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::ElementIndexTyper::get_int_type(int) const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:218: undefined reference to `OpenBabel::OBElements::GetCovalentRad(unsigned int)'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::GninaIndexTyper::get_atom_type_index(OpenBabel::OBAtom*) const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:88: undefined reference to `OpenBabel::OBAtomAtomIter::OBAtomAtomIter(OpenBabel::OBAtom*)'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:88: undefined reference to `OpenBabel::OBAtomAtomIter::operator++()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:95: undefined reference to `OpenBabel::OBElements::GetSymbol(unsigned int)'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:101: undefined reference to `OpenBabel::OBAtom::IsPolarHydrogen()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:113: undefined reference to `OpenBabel::OBAtom::IsHbondAcceptor()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:107: undefined reference to `OpenBabel::OBAtom::IsHbondAcceptor()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:104: undefined reference to `OpenBabel::OBAtom::IsAromatic() const'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::GninaVectorTyper::get_atom_type_vector(OpenBabel::OBAtom*, std::vector<float, std::allocator<float> >&) const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:389: undefined reference to `OpenBabel::OBAtom::GetPartialCharge()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:390: undefined reference to `OpenBabel::OBAtom::IsAromatic() const'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::ElementIndexTyper::get_type_radii() const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:238: undefined reference to `OpenBabel::OBElements::GetCovalentRad(unsigned int)'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::ElementIndexTyper::get_type_names[abi:cxx11]() const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:228: undefined reference to `OpenBabel::OBElements::GetName(unsigned int)'
../lib/libmolgrid.a(coordinateset.cpp.o): In function `libmolgrid::CoordinateSet::CoordinateSet(OpenBabel::OBMol*, libmolgrid::AtomTyper const&)':
/mnt/shared/releases/source/libmolgrid/src/coordinateset.cpp:30: undefined reference to `OpenBabel::OBMolAtomIter::OBMolAtomIter(OpenBabel::OBMol*)'
/mnt/shared/releases/source/libmolgrid/src/coordinateset.cpp:30: undefined reference to `OpenBabel::OBMolAtomIter::operator++()'
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_coordinateset_cpp.dir/build.make:108: recipe for target 'bin/test_coordinateset_cpp' failed
make[2]: *** [bin/test_coordinateset_cpp] Error 1
CMakeFiles/Makefile2:1083: recipe for target 'test/CMakeFiles/test_coordinateset_cpp.dir/all' failed
make[1]: *** [test/CMakeFiles/test_coordinateset_cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::ElementIndexTyper::get_atom_type_index(OpenBabel::OBAtom*) const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:211: undefined reference to `OpenBabel::OBElements::GetCovalentRad(unsigned int)'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::ElementIndexTyper::get_int_type(int) const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:218: undefined reference to `OpenBabel::OBElements::GetCovalentRad(unsigned int)'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::GninaIndexTyper::get_atom_type_index(OpenBabel::OBAtom*) const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:88: undefined reference to `OpenBabel::OBAtomAtomIter::OBAtomAtomIter(OpenBabel::OBAtom*)'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:88: undefined reference to `OpenBabel::OBAtomAtomIter::operator++()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:95: undefined reference to `OpenBabel::OBElements::GetSymbol(unsigned int)'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:101: undefined reference to `OpenBabel::OBAtom::IsPolarHydrogen()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:113: undefined reference to `OpenBabel::OBAtom::IsHbondAcceptor()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:107: undefined reference to `OpenBabel::OBAtom::IsHbondAcceptor()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:104: undefined reference to `OpenBabel::OBAtom::IsAromatic() const'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::GninaVectorTyper::get_atom_type_vector(OpenBabel::OBAtom*, std::vector<float, std::allocator<float> >&) const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:389: undefined reference to `OpenBabel::OBAtom::GetPartialCharge()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:390: undefined reference to `OpenBabel::OBAtom::IsAromatic() const'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::ElementIndexTyper::get_type_radii() const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:238: undefined reference to `OpenBabel::OBElements::GetCovalentRad(unsigned int)'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::ElementIndexTyper::get_type_names[abi:cxx11]() const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:228: undefined reference to `OpenBabel::OBElements::GetName(unsigned int)'
../lib/libmolgrid.a(coordinateset.cpp.o): In function `libmolgrid::CoordinateSet::CoordinateSet(OpenBabel::OBMol*, libmolgrid::AtomTyper const&)':
/mnt/shared/releases/source/libmolgrid/src/coordinateset.cpp:30: undefined reference to `OpenBabel::OBMolAtomIter::OBMolAtomIter(OpenBabel::OBMol*)'
/mnt/shared/releases/source/libmolgrid/src/coordinateset.cpp:30: undefined reference to `OpenBabel::OBMolAtomIter::operator++()'
../lib/libmolgrid.a(coord_cache.cpp.o): In function `libmolgrid::CoordCache::set_coords(char const*, libmolgrid::CoordinateSet&)':
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:148: undefined reference to `OpenBabel::OBConversion::OBConversion(std::istream*, std::ostream*)'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:149: undefined reference to `OpenBabel::OBMol::OBMol()'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:150: undefined reference to `OpenBabel::OBConversion::ReadFile(OpenBabel::OBBase*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:154: undefined reference to `OpenBabel::OBMol::AddHydrogens(bool, bool, double)'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:149: undefined reference to `OpenBabel::OBMol::~OBMol()'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:148: undefined reference to `OpenBabel::OBConversion::~OBConversion()'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:149: undefined reference to `OpenBabel::OBMol::~OBMol()'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:148: undefined reference to `OpenBabel::OBConversion::~OBConversion()'
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_gridmaker_cpp.dir/build.make:108: recipe for target 'bin/test_gridmaker_cpp' failed
make[2]: *** [bin/test_gridmaker_cpp] Error 1
CMakeFiles/Makefile2:1031: recipe for target 'test/CMakeFiles/test_gridmaker_cpp.dir/all' failed
make[1]: *** [test/CMakeFiles/test_gridmaker_cpp.dir/all] Error 2

and **test_gridmaker_cu**:

../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::ElementIndexTyper::get_atom_type_index(OpenBabel::OBAtom*) const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:211: undefined reference to `OpenBabel::OBElements::GetCovalentRad(unsigned int)'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::ElementIndexTyper::get_int_type(int) const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:218: undefined reference to `OpenBabel::OBElements::GetCovalentRad(unsigned int)'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::GninaIndexTyper::get_atom_type_index(OpenBabel::OBAtom*) const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:88: undefined reference to `OpenBabel::OBAtomAtomIter::OBAtomAtomIter(OpenBabel::OBAtom*)'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:88: undefined reference to `OpenBabel::OBAtomAtomIter::operator++()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:95: undefined reference to `OpenBabel::OBElements::GetSymbol(unsigned int)'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:101: undefined reference to `OpenBabel::OBAtom::IsPolarHydrogen()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:113: undefined reference to `OpenBabel::OBAtom::IsHbondAcceptor()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:107: undefined reference to `OpenBabel::OBAtom::IsHbondAcceptor()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:104: undefined reference to `OpenBabel::OBAtom::IsAromatic() const'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::GninaVectorTyper::get_atom_type_vector(OpenBabel::OBAtom*, std::vector<float, std::allocator<float> >&) const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:389: undefined reference to `OpenBabel::OBAtom::GetPartialCharge()'
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:390: undefined reference to `OpenBabel::OBAtom::IsAromatic() const'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::ElementIndexTyper::get_type_radii() const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:238: undefined reference to `OpenBabel::OBElements::GetCovalentRad(unsigned int)'
../lib/libmolgrid.a(atom_typer.cpp.o): In function `libmolgrid::ElementIndexTyper::get_type_names[abi:cxx11]() const':
/mnt/shared/releases/source/libmolgrid/src/atom_typer.cpp:228: undefined reference to `OpenBabel::OBElements::GetName(unsigned int)'
../lib/libmolgrid.a(coordinateset.cpp.o): In function `libmolgrid::CoordinateSet::CoordinateSet(OpenBabel::OBMol*, libmolgrid::AtomTyper const&)':
/mnt/shared/releases/source/libmolgrid/src/coordinateset.cpp:30: undefined reference to `OpenBabel::OBMolAtomIter::OBMolAtomIter(OpenBabel::OBMol*)'
/mnt/shared/releases/source/libmolgrid/src/coordinateset.cpp:30: undefined reference to `OpenBabel::OBMolAtomIter::operator++()'
../lib/libmolgrid.a(coord_cache.cpp.o): In function `libmolgrid::CoordCache::set_coords(char const*, libmolgrid::CoordinateSet&)':
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:148: undefined reference to `OpenBabel::OBConversion::OBConversion(std::istream*, std::ostream*)'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:149: undefined reference to `OpenBabel::OBMol::OBMol()'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:150: undefined reference to `OpenBabel::OBConversion::ReadFile(OpenBabel::OBBase*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:154: undefined reference to `OpenBabel::OBMol::AddHydrogens(bool, bool, double)'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:149: undefined reference to `OpenBabel::OBMol::~OBMol()'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:148: undefined reference to `OpenBabel::OBConversion::~OBConversion()'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:149: undefined reference to `OpenBabel::OBMol::~OBMol()'
/mnt/shared/releases/source/libmolgrid/src/coord_cache.cpp:148: undefined reference to `OpenBabel::OBConversion::~OBConversion()'
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_gridmaker_cu.dir/build.make:108: recipe for target 'bin/test_gridmaker_cu' failed
make[2]: *** [bin/test_gridmaker_cu] Error 1
CMakeFiles/Makefile2:1005: recipe for target 'test/CMakeFiles/test_gridmaker_cu.dir/all' failed
make[1]: *** [test/CMakeFiles/test_gridmaker_cu.dir/all] Error 2

Could you please help? I am wondering what I am doing wrong. 
I am installing on Ubuntu 18.04. 

Thank you and Best Regards,
Davide

**Comment by dkoes** [comment]
OPENBABEL3_LIBRARIES is not a directory but the actual library (e.g.  `/usr/local/lib/libopenbabel.so`)

And if you think calling it LIBRARIES when it refers to a single library is confusing, I agree, but this is the cmake convention.
