### ISSUE TITLE
Fail to import the MolDataset

### ISSUE THREAD

**Issue by wenxianxian** [gnina/libmolgrid#59]
Hi,

I would like to use the MolDataset class shown in your document (https://gnina.github.io/libmolgrid/python/index.html?highlight=merge_coordinates#molgrid.torch_bindings.MolDataset), but it fails to import this class. I have tried both installing from the source (version 0.2.1) and installing by pip. They all show the ImportError as the following:
ImportError: cannot import name 'MolDataset' from 'molgrid.torch_bindings' (/usr/local/lib/python3.7/dist-packages/molgrid-0.2.1.dev35+g281b3c3-py3.7.egg/molgrid/torch_bindings.py) 
(pip install version: ImportError: cannot import name 'MolDataset' from 'molgrid.torch_bindings' (/opt/tiger/miniconda/lib/python3.7/site-packages/molgrid/torch_bindings.py))

Could you please help me with this issue?

Thanks!

**Comment by dkoes** [comment]
We haven't included this feature in a release yet - it isn't quite clear what the right use case and API for this is.  Can you explain what you are doing and how you want to use this?

**Comment by yangxiufengsia** [comment]
@dkoes Prof.Koes, I plan to use moldataset for pytorch distributed data parallel, @drewnutt replied me that I can use it by building from source. Actually, I don't know how to recompile it from source, are there any documents for tutorial? Thanks a lot.

**Comment by drewnutt** [comment]
The main `README.md` has a step by step instruction on how to build from source.

**Comment by yangxiufengsia** [comment]
thanks for quick reply. OK, I will first try that.
