### ISSUE TITLE
What is the difference between molgrid in libmolgrid and gnina?

### ISSUE THREAD

**Issue by yamasakih** [gnina/libmolgrid#6]
Hi,

I would like to use this repository with great interest in your libmolgrid.

I want to ask what is the difference between molgrid in libmolgrid and gnina.
Is it okay to understand that `molgrid` in libmolgrid is implemented with reference to the function to generate grid in `gnina`?

And you read "Do not use" in the Readme.
Is it written in the meaning of not guaranteeing operation?
Is it possible to use it under an Apache license? 

Thanks for your help.

**Comment by dkoes** [comment]
libmolgird has factored our gridding code into a standalone library.  The current version of gnina uses libmolgrid as a dependency.

We need to do a little bit more work with documentation and adding a few features before the first release, but you can use libmolgrid as it is now.  See:
https://github.com/gnina/libmolgrid/blob/master/test/test_torch_cnn.py
for a pytorch example.

**Comment by yamasakih** [comment]
Thx!

I'm very glad to have an example because I thought that I implemented it with Pytorch.

In addition to libmolgrid, should I compile gninagrid and preprocess the data?

**Comment by dkoes** [comment]
You do not pregenerate grids - that's the point of molgrid to generate them on the fly. It's important to be able to have random rotations and translations.  You can preprocess molecular data into gninatypes files and a create a single molcache with create_caches2.py for faster training if you are fine using gninatypes.

**Comment by yamasakih** [comment]
Thank you for the detailed explanation.

I only have to use molgrid. It's very easy :)

There are many useful functions in the gnina/scripts repository.
I will look into it for study.

Thank you very much!
