### ISSUE TITLE
Does libmolgrid allows pytorch distribtued data parallel?

### ISSUE THREAD

**Issue by yangxiufengsia** [gnina/libmolgrid#60]

**Comment by drewnutt** [comment]
Pytorch's Distributed Data Parallel (DDP) will generally require you to use a Pytorch `DataLoader` with a `DistributedDataSampler`, this is not possible if you are using `molgrid.ExampleProvider` as the `ExampleProvider` does the sampling and loading. However, the `molgrid.MolDataset` will function identically to a mappable Pytorch Dataset, allowing you to use it within a `DataLoader` with a `DistributedDataSampler`. 

`molgrid.MolDataset` is an unreleased feature so you must compile libmolgrid from source to be able to use it.

**Comment by yangxiufengsia** [comment]
Thanks a lot. Do you plan to release molgrid.moldataset in the near future? Where Can I find detailed documentation for usage of molgrid.Moldataset? Again, thank you.

**Comment by yangxiufengsia** [comment]
I found a source code here : 
class MolDataset(torch.utils.data.Dataset):
    '''A pytorch mappable dataset for molgrid training files.'''
    def __init__(self, *args, **kwargs):
        '''Initialize mappable MolGridDataset.  
        :param input(s): File name(s) of training example files 
        :param typers: A tuple of AtomTypers to use
        :type typers: tuple
        :param cache_structs: retain coordinates in memory for faster training
        :param add_hydrogens: protonate molecules read using openbabel
        :param duplicate_first: clone the first coordinate set to be paired with each of the remaining (receptor-ligand pairs)
        :param make_vector_types: convert index types into one-hot encoded vector types
        :param data_root: prefix for data files
        :param recmolcache: precalculated molcache2 file for receptor (first molecule); if doesn't exist, will look in data _root
        :param ligmolcache: precalculated molcache2 file for ligand; if doesn't exist, will look in data_root
        '''

        if 'typers' in kwargs:
            typers = kwargs['typers']
            del kwargs['typers']
            self.examples = mg.ExampleDataset(*typers,**kwargs)
            self.typers = typers
        else:
            self.examples = mg.ExampleDataset(**kwargs)
            self.typers = None
        self.types_files = list(args)
        self.examples.populate(self.types_files)
            
        self.num_labels = self.examples.num_labels()

        
    def __len__(self):
        return len(self.examples)
    
    def __getitem__(self, idx):
        ex = self.examples[idx]
        center = torch.tensor([i for i in ex.coord_sets[-1].center()])
        coordinates = ex.merge_coordinates()
        if coordinates.has_vector_types() and coordinates.size() > 0:
            atomtypes = torch.tensor(coordinates.type_vector.tonumpy(),dtype=torch.long).type('torch.FloatTensor')
        else:
            atomtypes = torch.tensor(coordinates.type_index.tonumpy(),dtype=torch.long).type('torch.FloatTensor')
        coords = torch.tensor(coordinates.coords.tonumpy())
        radii = torch.tensor(coordinates.radii.tonumpy())
        labels = [ex.labels[lab] for lab in range(self.num_labels)]
        return center, coords, atomtypes, radii, labels
    
    def __getstate__(self):
        settings = self.examples.settings()
        keyword_dict = {sett: getattr(settings, sett) for sett in dir(settings) if not sett.startswith('__')}
        if self.typers is not None: ## This will fail if self.typers is not none, need a way to pickle AtomTypers
            raise NotImplementedError('MolDataset does not support pickling when not using the default Gnina atom typers, this uses %s'.format(str(self.typers)))
            keyword_dict['typers'] = self.typers
        return keyword_dict, self.types_files

    def __setstate__(self,state):
        kwargs=state[0]
        
        if 'typers' in kwargs:
            typers = kwargs['typers']
            del kwargs['typers']
            self.examples = mg.ExampleDataset(*typers, **kwargs)
            self.typers = typers
        else:
            self.examples = mg.ExampleDataset(**kwargs)
            self.typers = None
        self.types_files = list(state[1])
        self.examples.populate(self.types_files)

        self.num_labels = self.examples.num_labels()


are there any ways to replace the example_provide function to this moldataset without recompile the source code? Thanks

**Comment by drewnutt** [comment]
You should be able to change `torch_bindings.py` that was created when you built libmolgrid from source. This should be located somewhere in your python `dist-packages` directory. For instance my file can be found in `/usr/local/lib/python3.8/dist-packages/molgrid-0.2.1.dev47+g2375f0b-py3.8.egg/molgrid/` on Ubuntu 20.04

**Comment by yangxiufengsia** [comment]
Thanks a lot. I will try build libmolgrid from source first.

**Comment by yangxiufengsia** [comment]
Hi, when I install libmolgrid from source (without root), there are a lot of errors related to boost, python and openbabel. I want to ask if you plan to release a guide/readme describing how to install libmolgrid from source without root? That will be very helpful. Thank you.

**Comment by dkoes** [comment]
You need to have the dependencies.  You can build this from source in your local directory if you do not have super user permission.

**Comment by yangxiufengsia** [comment]
Thanks prof.koes. Finally, I successfully installed without root. The process should be very careful.

**Comment by yangxiufengsia** [comment]
Hi, 
I have tried MolDataset, but couldn't understand how to use the output of collateMolDataset(batch). I plan to use the output for creating grid by using gridmaker, but could't find related documents. Are there any related documents or could you provide some examples about how to use collateMolDataset? thanks a lot.

**Comment by dkoes** [comment]
1. The collate function is for use with python dataloaders, which require such a function.  For example:
```
    torch_loader = torch.utils.data.DataLoader(      
     m, batch_size=8,collate_fn=molgrid.MolDataset.collateMolDataset)
```
2. Atom typers determine what channel(s) atoms should have density placed in.  A given atom typer will generate a fixed number of types (which you can get with `num_types`).  There are default typers used if you don't specify one.

**Comment by yangxiufengsia** [comment]
Hi Prof. koes. thanks a lot for sovling my issues. 
I got "engths, centers, lcoords, ltypes, lradii, labels" parameters after calling MolDataset and lollateMolDataset. Then I used coord2grid to get grid tensors so that I can use these tensors as input for training. 

``
gridder1 = molgrid.torch_bindings.Coords2Grid(gmaker=molgrid.GridMaker(resolution=0.5,dimension=23.5, ),center=(0,0,0))

grid1 = gridder1.forward(lcoords, ltypes, lradii)
``

I got the following error:
``
RuntimeError: Invalid input dimensions in forward of Coords2Grid
``

I checked the shapes of coords, types and radii, the examples are listed as follows. I found the len(radii.shape) should be 2 but I obtained 3:
``
check train_loader: 182 torch.Size([10, 12718, 3]) torch.Size([10, 12718]) torch.Size([10, 12718, 1])

check train_loader: 183 torch.Size([10, 6981, 3]) torch.Size([10, 6981]) torch.Size([10, 6981, 1])

check train_loader: 188 torch.Size([10, 23077, 3]) torch.Size([10, 23077]) torch.Size([10, 23077, 1])

check train_loader: 184 torch.Size([10, 15606, 3]) torch.Size([10, 15606]) torch.Size([10, 15606, 1])

``

Could you help this issue? How to correctly use coord2grid? Thanks a lot!

**Comment by yangxiufengsia** [comment]
By the way, are there any code examples about how to make grid tensors from coords, types adn radii from MolDataset? thanks !

**Comment by dkoes** [comment]
You can look through the tests for example of usage.

**Comment by yangxiufengsia** [comment]
thanks a lot. I think there is a bug in function BatchedCoords2GridFunction(torch.autograd.Function) of torch_bindings. 
In line 107:    shape = gmaker.grid_dimensions(types.shape[2]) #ntypes == nchannels 
The len of shape of types obtained from collateMolDataset is 2, so, types.shape[2] is out of index in line 107. 
Is it possible to check if this is a bug? Thanks a lot.

**Comment by dkoes** [comment]
The types are assumed to be vector types of size NxT where N is the number of atoms and T is the number of types.  You can convert index types to vector types with `make_vector_types`
https://gnina.github.io/libmolgrid/python/index.html#molgrid.CoordinateSet.make_vector_types

**Comment by yangxiufengsia** [comment]
Thanks a lot for helping solve the issue.
 I tried  `atomtypes = torch.tensor(coordinates.type_index.make_vector_types().tonumpy(),dtype=torch.long).type('torch.FloatTensor')`
but the error happens: MGrid1f has no attribute make_vector_types. 
I think the usage of make_vector_types() is not correct.  Could you tell how to correctly use `make_vector_types()` for translating `type_index` to vector types?  Thanks in advance.

**Comment by dkoes** [comment]
You are making a tensor, `make_vector_types` is a method of a CoordinateSet

**Comment by yangxiufengsia** [comment]
Oh, I just noticed. I should check it carefully. Finally, it works. Thanks a lot.
