### ISSUE TITLE
Behavior for only ligands in types file and ExampleProvider

### ISSUE THREAD

**Issue by mgm-14392** [gnina/libmolgrid#64]
Hi,

From what I understood, when I have a types file with protein-ligand pairs (3rd and 4th columns) and I use this types file to populate an ExampleProvider, each example will have 28 channels. The first 14 are the defaultGninaReceptorTyper and the next 14 are the defaultGninaLigandTyper.

What is the behavior when I have a types file that only contains a ligand (3rd and last column)? My guess is that the channels will be the defaultGninaReceptorTyper.

Since I only have a ligand, I will only have 14 channels `ddims = gmaker.grid_dimensions(14)` but how can I make sure that the ligand channels in the Example will be the defaultGninaLigandTyper ?

Thank you!

**Comment by dkoes** [comment]
You are correct that if you don't specify the typers, the assumption is the first file is a receptor and defaultGninaReceptorTyper is used.  If you want only ligand types, you need to create an ExampleProvider with a single explicit typer:
```
provider = molgrid.ExampleProvider(molgrid.defaultGninaLigandTyper)
```

**Comment by mgm-14392** [comment]
I see. Thank you Dr. Koes!! I will close the issue now.
