### ISSUE TITLE
Is it possible to know the set of examples next_batch extracts?

### ISSUE THREAD

**Issue by shikhar2333** [gnina/libmolgrid#68]
`batch = e.next_batch(batch_size)`
In the above code, is it possible to know exactly which set of examples the **ExampleProvider** object extracts?

**Comment by dkoes** [comment]
Inspect the `src` property.

**Comment by shikhar2333** [comment]
The `src` folder?

**Comment by dkoes** [comment]
The `CoordinateSet` object has a `src` property that contains the filename of the source of the coordinates, if available.

**Comment by shikhar2333** [comment]
Thanks, this worked.
