### ISSUE TITLE
How to voxelize a single .pdb file?

### ISSUE THREAD

**Issue by mangalp** [gnina/libmolgrid#69]
Hello,  
It appears that libmolgrid is a very powerful library and it being open source is a big plus for the community.  But as a beginner to the field, it seems quite non-intuitive (with minimal examples and little documentation). I am struggling to perform a rather simple task. For example, if I have a protein file in .pdb format, how do I voxelize it? Looking at the examples, it seems that the code accepts .gninatype files but it does not explain anywhere how to get such .gninatype files in the first place? Provided .pdb files are most common, it would serve the community well if you could please provide a minimalistic (but complete code) example for processing a single .pdb file to generate a Tensor. 
I looked at other issues and it seems that someone else asked it as well. Although you have provided some comments there, it is still quite obscure for me as a complete beginner to the field.

I am happy to contribute to the documentation for the same publicly, if possible, to help others in the future with similar questions. Thank you.

**Comment by dkoes** [comment]
I agree we need better documentation, especially for this use case.  Issue #56 touches on this.  Here is an example:
https://colab.research.google.com/drive/1L9XlaLgsBFWlMtgvyLU_oG25QcigHkL6?usp=sharing

**Comment by mangalp** [comment]
Thank you for the nice example colab notebook. This helps me a lot.
