### ISSUE TITLE
how to make the grid density much sharper?

### ISSUE THREAD

**Issue by yangxiufengsia** [gnina/libmolgrid#72]
Hi,
The grid density of compounds with complex structure are well overlapped. Because of it, it is difficult to generate such compounds using liGAN. So I would like to sharpen the grid density. Could you please tell me how to sharpen the grid density in Libmolgrid? Thanks a lot.

**Comment by dkoes** [comment]
Reduce the radius of the atoms.

**Comment by yangxiufengsia** [comment]
Thanks a lot, I will try.
