### ISSUE TITLE
Protein only

### ISSUE THREAD

**Issue by JoshuaMeyers** [gnina/libmolgrid#76]
Hey David,

I am only interested in the protein channels but I would still like to center on the centroid of a ligand (or pseudo-ligand).

- I have a working example where I throw away the final 14 channels but this seems like wasted calculation
- I have also tried using the NullIndexTyper() for the ligand and while this does only calculate protein channels, it removes the ability to calculate the centroid (and therefore the voxels end up in the wrong place) – a fix for this could be to read the ligand file separately using rdkit and transform using `gmaker.forward` but I bet the library allows a smarter way!

What should my approach be here? Many thanks again

**Comment by dkoes** [comment]
Sorry for the long delay...

The center calculation only considers typed atoms, which is why the NullTyper won't work.  You will need to construct grids directly from the receptor coordinate set rather than the full example.  For example, assuming `ex` is an `Example` with a protein and ligand:
```
gmaker.forward(ex.coord_sets[1].center(), ex.coord_sets[0], mgridout)
```

**Comment by JoshuaMeyers** [comment]
Hey @dkoes thanks for the reply, I don't quite understand even with the above setup I am seeing a zero center, your explanation makes sense but I don't get the solution. Here's some more concrete code

```
examples = molgrid.ExampleDataset(
    molgrid.defaultGninaReceptorTyper,
    molgrid.defaultGninaLigandTyper,
#     molgrid.NullIndexTyper(),
    data_root=example_data_root,
)
examples.populate(os.path.join(POCKR_REPO_ROOT, 'pockr/tests/test_data/simple_test.types'))

gmaker = molgrid.GridMaker(resolution=1.0, dimension=23, binary=False,
    radius_type_indexed=False, radius_scale=1.5, gaussian_radius_multiple=1.0)
shape = gmaker.grid_dimensions(examples.num_types())

example = examples[0]
coords = example.coord_sets[-1].coords.tonumpy()
center = example.coord_sets[-1].center()
print('the coordinates are empty?: ', not len(coords))
print('the center is calcualted as: ', list(center))

grid = molgrid.MGrid4f(*shape)
gmaker.forward(
    center,
    example.coord_sets[0],
    grid.cpu(),
#     random_translation=0,  # also it seems you cannot use these flags while specifying a center?
#     random_rotation=False,
)
features = np.array([grid.tonumpy()])
features.shape
```
output using the default typers:
```
the coordinates are empty?:  False
the center is calcualted as:  [48.474369049072266, 63.45606994628906, -6.453033924102783]
(1, 28, 24, 24, 24)
```
output using the null typer
```
the coordinates are empty?:  True
the center is calcualted as:  [0.0, 0.0, 0.0]
(1, 14, 24, 24, 24)
```

thanks in advance

**Comment by JoshuaMeyers** [comment]
Thanks a lot @dkoes. Works great! 🙏
