### ISSUE TITLE
Consistency of Voxels from PDB format versus gninatypes

### ISSUE THREAD

**Issue by JoshuaMeyers** [gnina/libmolgrid#78]
Hey Again, I've run into another point of confusion. I had expected that generating voxels from the pdb receptor file, and running gninatyper before generating voxels from gninatypes files should produce the same voxel output (with no transform/rotate). But I am not seeing that (I am actually seeing many more voxels activated in the PDB version), am I wrong to expect this behaviour?

Something that would help to debug would be some documentation on the format of the `.gninatypes` file. It seems to be binary encoded xyz coordinates plus a type and yet I am not able to decode it. I have tried this on the `10gs_docked_0.gninatypes` example
```
import struct
with open('/Users/jmeyers/Downloads/10gs_docked_0.gninatypes', 'rb') as f:
    for _, line in enumerate(f):
        print(struct.unpack('fffi', line[:16]))  # this does not work as line is not 16 bytes
```

I can provide code and examples if its helpful, but just a high level question at this point.

Thanks in advance, J.

**Comment by dkoes** [comment]
https://github.com/gnina/scripts/blob/master/types2xyz.py
will convert a gninatypes file to an xyz file.
You should get the same densities, assuming you are using the same typer and have the same center.

**Comment by JoshuaMeyers** [comment]
Hey @dkoes thanks for your reply. `types2xyz.py` has been useful for diving into the issue. Would be helpful to get your thoughts on whether there is anything wrong here:

- we took `REC.pdb` from your data/ directory, and ran gninatyper (using the dockerhub gnina image) to generate `REC.gninatypes`
- We have moved towards assessing just the example object and ensuring that the same number of atoms are in both REC.pdb and REC.gninatypes (removing the complexity of the grid and its center)
- There are 1685 unique xyz coordinates in REC.pdb, while REC.gninatypes has 3308 unique xyz coordinates using `types2xyz.py`.

Why would this be the case, many thanks in advance

**Comment by JoshuaMeyers** [comment]
Apologies ✋ , we have discovered that the difference in atom count is due to the addition of polar hydrogens by openbabel which are written to xyz but are not present in the ex.coord_sets.coords

**Comment by JoshuaMeyers** [comment]
Hey @dkoes okay we think we've pinpointed the issue. It seems that the ExampleDataset object when given `.gninatypes` structure files, assumes that they were written using the `gninaDefaultIndexTyper()` and attempts to ignore hydrogens (index 0 and 1) on loading. We did not realise that the gninatypes format is intended just for this typer, can you confirm this is the case? 

In our case, we are using the `defaultGninaReceptorTyper()` and have written our own gninatyper to write this to binary. We still find that our first 'type' is still dropped by ExampleDataset (but in our case this corresponds to "0_AliphaticCarbonXSHydrophobe" which we'd like to keep!). A hack to solve this would be to add "Hydrogen" and "PolarHydrogen" to the defaultGnina as these guys have done: https://github.com/devalab/DeepPocket/blob/main/gninamap. Is this solution sensible or are there other implications here?

**Comment by dkoes** [comment]
You need to provide your own typer to the ExampleProvider.  This is what maps between the numbers in the file and ultimate type indices.  For example:
```
t = molgrid.SubsettedGninaTyper([[0,1],[2,3,4,5]],catchall=False)
ex = molgrid.ExampleProvider(t)
```
This will map anything with indices 0 or 1 to zero and any atom with 2/3/4/5 to one and drop all other types (if catchall=True, all other types would be mapped to index 2).  Note that the type also determines the radius of the atom (unless you are setting it separately).  As long as gnina types are expressive enough for you, I would keep the gninatypes files as they are and remap to the desired typing.

**Comment by JoshuaMeyers** [comment]
Thanks @dkoes that solves our issue. We will write to gninatypes using the original `gninaDefaultIndexTyper` and remap to the desired types using the `defaultGninaReceptorTyper` which we provide to `ExampleDataset`/`ExampleProvider`. Thanks again!
