### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by kadiliissaar** [gnina/libmolgrid#85]
Hello!
I have been trying to install the library as per your instructions.

1. When using:
pip install molgrid
I received the following message:
ERROR: Could not find a version that satisfies the requirement molgrid (from versions: none)
ERROR: No matching distribution found for molgrid

2. When using:
conda install -c jsunseri molgrid
I received the following error:
PackagesNotFoundError: The following packages are not available from current channels:
  - molgrid
  
I tried this in a freshly created environment (python 3.7).  Could you please advise how I should proceed to get it installed? In the future, I am interested in integrating it with the following repository: https://github.com/fimrie/DenseFS

Best wishes,
Kadi

**Comment by kadiliissaar** [comment]
Thank you @dkoes. It's:
WARNING: Package(s) not found: molgrid
Yes, having a conda package would certainly be helpful.

**Comment by ksaar-transitionbio** [comment]
Hello @Luc1100 and @dkoes,

Do you have an estimate when updated conda package may be available?

Thank you and best wishes,
Kadi

**Comment by kadiliissaar** [comment]
Hello @Luc1100 and @dkoes,

Do you have an estimate when updated conda package may be available?

Thank you and best wishes,
Kadi

**Comment by Luc1100** [comment]
@kadiliissaar The package can be found here: https://anaconda.org/gnina/molgrid
 I have not done much testing other than checking that it imports. Let me know if you have an issues.

**Comment by kadiliissaar** [comment]
Thank you @Luc1100! I see the anaconda page only lists Linux, are you planning on making it MacOS compatible as well?

**Comment by Luc1100** [comment]
@kadiliissaar I uploaded one, however, I cannot say if it works at all as I have an M1 Mac and libmolgrid requires CUDA.

**Comment by kadiliissaar** [comment]
Fair enough! I am just trying conda install on a linux machine but the environment resolving has been going on for 10+ mins. Do you know why this may be?

**Comment by Luc1100** [comment]
@kadiliissaar Are you working in a clean environment? I tested on another linux machine and it installed pretty fast.

**Comment by kadiliissaar** [comment]
Thank you @Luc1100. I tried now in a clean environment (with python 3.9) and the installation went fine.
However, when trying to import molgrid, I received the following message:

from .molgrid import *
ImportError: libboost_python39.so.1.73.0: cannot open shared object file: No such file or directory

Do you know why this may be?

**Comment by danielegrattarola** [comment]
Hi, 

any chance of getting the PyPi wheel updated to support MacOS too? 

Thanks!
