### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by xiaolinpan** [gnina/libmolgrid#9]
Could you tell me how to install libmolgrid into python? Thank you! it's not work when I use "python setup.py install" to install.

running install
running build
running build_py
error: package directory '${CMAKE_CURRENT_BINARY_DIR}/molgrid' does not exist

**Comment by dkoes** [comment]
I have updated the README to include installation instructions.  You will need CUDA installed and the very latest version of openbabel.

**Comment by xiaolinpan** [comment]
Do you know why such a mistake occurs? When i use cmake to install molgrid. Thank you!


Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/pxl/localhome/libmolgrid/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_ab8c5/fast && /usr/bin/make -f CMakeFiles/cmTC_ab8c5.dir/build.make CMakeFiles/cmTC_ab8c5.dir/build
make[1]: Entering directory '/home/pxl/localhome/libmolgrid/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ab8c5.dir/src.c.o
/usr/bin/cc   -fPIC -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_ab8c5.dir/src.c.o   -c /home/pxl/localhome/libmolgrid/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_ab8c5
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ab8c5.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_ab8c5.dir/src.c.o  -o cmTC_ab8c5
CMakeFiles/cmTC_ab8c5.dir/src.c.o: In function `main':
src.c:(.text+0x3e): undefined reference to `pthread_create'
src.c:(.text+0x4a): undefined reference to `pthread_detach'
src.c:(.text+0x5b): undefined reference to `pthread_join'
src.c:(.text+0x6f): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_ab8c5.dir/build.make:86: recipe for target 'cmTC_ab8c5' failed
make[1]: *** [cmTC_ab8c5] Error 1
make[1]: Leaving directory '/home/pxl/localhome/libmolgrid/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_ab8c5/fast' failed
make: *** [cmTC_ab8c5/fast] Error 2


Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/pxl/localhome/libmolgrid/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_201ca/fast && /usr/bin/make -f CMakeFiles/cmTC_201ca.dir/build.make CMakeFiles/cmTC_201ca.dir/build
make[1]: Entering directory '/home/pxl/localhome/libmolgrid/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_201ca.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_201ca.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.15/Modules/CheckFunctionExists.c
Linking C executable cmTC_201ca
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_201ca.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_201ca.dir/CheckFunctionExists.c.o  -o cmTC_201ca -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_201ca.dir/build.make:86: recipe for target 'cmTC_201ca' failed
make[1]: *** [cmTC_201ca] Error 1
make[1]: Leaving directory '/home/pxl/localhome/libmolgrid/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_201ca/fast' failed
make: *** [cmTC_201ca/fast] Error 2

**Comment by xiaolinpan** [comment]
> Looks like it can't find pthreads. What operating system and cmake version are you using?

ubuntu 18.04 cmake version 3.15, and cmake installed by conda, Maybe the error occured by it

**Comment by dkoes** [comment]
I updated the docker container to 18.04 and cmake 3.15 without getting these errors.  Perhaps you could compare to your install to see what is different?
https://hub.docker.com/r/dkoes/gnina
