### ISSUE TITLE
Cannot pip install

### ISSUE THREAD

**Issue by emarsh25** [gnina/libmolgrid#90]
ERROR: Could not find a version that satisfies the requirement molgrid==0.5.2 (from versions: none)
ERROR: No matching distribution found for molgrid==0.5.2

Cannot seem to install this package. I also tried to conda install. Neither worked

**Comment by dkoes** [comment]
What operating system and python version are you using?

**Comment by emarsh25** [comment]
Mac M1 and Python 3.9

**Comment by dkoes** [comment]
CUDA is required, won't work on Mac.
