### ISSUE TITLE
Pip Installation Error

### ISSUE THREAD

**Issue by drorhunvural** [gnina/libmolgrid#93]
I'm using Visual Studio Code. When I type pip install molgrid I am getting the following error. 

`pip install molgrid`

_ERROR: Could not find a version that satisfies the requirement molgrid (from versions: none)
ERROR: No matching distribution found for molgrid_

Where could the problem throw from?

Note: I installed CUDA and Cmake

**Python Version**
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Operating System**
The Windows 11

**Comment by dkoes** [comment]
Windows isn't supported.
